### ISSUE TITLE
Dangling LinkedIn Links

### ISSUE THREAD

**Issue by yvesyil** [notyiming/yimingtan.io#1]
### Fix Your LinkedIn Links My Guy!

Try this:
https://www.linkedin.com/in/tanyiming/

**Comment by peepojiji** [comment]
this is an old website, not really being used anymore. But still worth updating the link. Thanks!

**Comment by peepojiji** [comment]
> this is an old website, not really being used anymore. But still worth updating the link. Thanks!

visit www.tanyiming.com for the latest site
